# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptimineExport(object):
    def setupUi(self, OptimineExport):
        OptimineExport.setObjectName("OptimineExport")
        OptimineExport.resize(628, 596)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptimineExport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pressureFileLabel = QtWidgets.QLabel(OptimineExport)
        self.pressureFileLabel.setObjectName("pressureFileLabel")
        self.gridLayout.addWidget(self.pressureFileLabel, 0, 0, 1, 1)
        self.pressureFileButton = QtWidgets.QToolButton(OptimineExport)
        self.pressureFileButton.setObjectName("pressureFileButton")
        self.gridLayout.addWidget(self.pressureFileButton, 0, 3, 1, 1)
        self.acousticsFileLabel = QtWidgets.QLabel(OptimineExport)
        self.acousticsFileLabel.setEnabled(False)
        self.acousticsFileLabel.setObjectName("acousticsFileLabel")
        self.gridLayout.addWidget(self.acousticsFileLabel, 1, 0, 1, 1)
        self.acousticsFileButton = QtWidgets.QToolButton(OptimineExport)
        self.acousticsFileButton.setEnabled(False)
        self.acousticsFileButton.setObjectName("acousticsFileButton")
        self.gridLayout.addWidget(self.acousticsFileButton, 1, 3, 1, 1)
        self.pressureLineEdit = QtWidgets.QLineEdit(OptimineExport)
        self.pressureLineEdit.setObjectName("pressureLineEdit")
        self.gridLayout.addWidget(self.pressureLineEdit, 0, 1, 1, 2)
        self.acousticsLineEdit = QtWidgets.QLineEdit(OptimineExport)
        self.acousticsLineEdit.setEnabled(False)
        self.acousticsLineEdit.setObjectName("acousticsLineEdit")
        self.gridLayout.addWidget(self.acousticsLineEdit, 1, 1, 1, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(OptimineExport)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.testReportLabel = QtWidgets.QLabel(self.groupBox)
        self.testReportLabel.setObjectName("testReportLabel")
        self.gridLayout_2.addWidget(self.testReportLabel, 0, 0, 1, 1)
        self.testReportLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.testReportLineEdit.setObjectName("testReportLineEdit")
        self.gridLayout_2.addWidget(self.testReportLineEdit, 0, 1, 1, 1)
        self.pressureVesselLabel = QtWidgets.QLabel(self.groupBox)
        self.pressureVesselLabel.setObjectName("pressureVesselLabel")
        self.gridLayout_2.addWidget(self.pressureVesselLabel, 0, 2, 1, 1)
        self.pressureVesselLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.pressureVesselLineEdit.setText("")
        self.pressureVesselLineEdit.setObjectName("pressureVesselLineEdit")
        self.gridLayout_2.addWidget(self.pressureVesselLineEdit, 0, 3, 1, 1)
        self.operatorLabel = QtWidgets.QLabel(self.groupBox)
        self.operatorLabel.setObjectName("operatorLabel")
        self.gridLayout_2.addWidget(self.operatorLabel, 1, 0, 1, 1)
        self.operaatorLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.operaatorLineEdit.setObjectName("operaatorLineEdit")
        self.gridLayout_2.addWidget(self.operaatorLineEdit, 1, 1, 1, 1)
        self.pressureTransducerLabel = QtWidgets.QLabel(self.groupBox)
        self.pressureTransducerLabel.setObjectName("pressureTransducerLabel")
        self.gridLayout_2.addWidget(self.pressureTransducerLabel, 1, 2, 1, 1)
        self.pressureTransducerLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.pressureTransducerLineEdit.setText("")
        self.pressureTransducerLineEdit.setObjectName("pressureTransducerLineEdit")
        self.gridLayout_2.addWidget(self.pressureTransducerLineEdit, 1, 3, 1, 1)
        self.startTimeLabel = QtWidgets.QLabel(self.groupBox)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.gridLayout_2.addWidget(self.startTimeLabel, 2, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setCalendarPopup(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 2, 1, 1, 1)
        self.endTimeLabel = QtWidgets.QLabel(self.groupBox)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.gridLayout_2.addWidget(self.endTimeLabel, 2, 2, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_2.setReadOnly(True)
        self.dateTimeEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_2.setCalendarPopup(False)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 2, 3, 1, 1)
        self.durationLabel = QtWidgets.QLabel(self.groupBox)
        self.durationLabel.setObjectName("durationLabel")
        self.gridLayout_2.addWidget(self.durationLabel, 3, 0, 1, 1)
        self.duration = QtWidgets.QLabel(self.groupBox)
        self.duration.setObjectName("duration")
        self.gridLayout_2.addWidget(self.duration, 3, 1, 1, 1)
        self.pressureUnitLabel = QtWidgets.QLabel(self.groupBox)
        self.pressureUnitLabel.setObjectName("pressureUnitLabel")
        self.gridLayout_2.addWidget(self.pressureUnitLabel, 3, 2, 1, 1)
        self.pressureUnit = QtWidgets.QLabel(self.groupBox)
        self.pressureUnit.setObjectName("pressureUnit")
        self.gridLayout_2.addWidget(self.pressureUnit, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(OptimineExport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.partNumberLabel = QtWidgets.QLabel(self.groupBox_2)
        self.partNumberLabel.setObjectName("partNumberLabel")
        self.gridLayout_3.addWidget(self.partNumberLabel, 0, 0, 1, 1)
        self.partNumberLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.partNumberLineEdit.setText("")
        self.partNumberLineEdit.setObjectName("partNumberLineEdit")
        self.gridLayout_3.addWidget(self.partNumberLineEdit, 0, 1, 1, 1)
        self.serialNumberLabel = QtWidgets.QLabel(self.groupBox_2)
        self.serialNumberLabel.setObjectName("serialNumberLabel")
        self.gridLayout_3.addWidget(self.serialNumberLabel, 0, 2, 1, 1)
        self.serialNumberLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.serialNumberLineEdit.setText("")
        self.serialNumberLineEdit.setObjectName("serialNumberLineEdit")
        self.gridLayout_3.addWidget(self.serialNumberLineEdit, 0, 3, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 1, 0, 1, 4)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(OptimineExport)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fullScaleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.fullScaleSpinBox.setToolTip("")
        self.fullScaleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fullScaleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fullScaleSpinBox.setDecimals(3)
        self.fullScaleSpinBox.setSingleStep(0.01)
        self.fullScaleSpinBox.setProperty("value", 10.013)
        self.fullScaleSpinBox.setObjectName("fullScaleSpinBox")
        self.gridLayout_4.addWidget(self.fullScaleSpinBox, 0, 1, 1, 1)
        self.fullScaleLabel = QtWidgets.QLabel(self.groupBox_3)
        self.fullScaleLabel.setObjectName("fullScaleLabel")
        self.gridLayout_4.addWidget(self.fullScaleLabel, 0, 0, 1, 1)
        self.zeroBalanceSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.zeroBalanceSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zeroBalanceSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.zeroBalanceSpinBox.setDecimals(3)
        self.zeroBalanceSpinBox.setMinimum(-99.0)
        self.zeroBalanceSpinBox.setSingleStep(0.01)
        self.zeroBalanceSpinBox.setProperty("value", 0.013)
        self.zeroBalanceSpinBox.setObjectName("zeroBalanceSpinBox")
        self.gridLayout_4.addWidget(self.zeroBalanceSpinBox, 0, 3, 1, 1)
        self.zeroBalanceLabel = QtWidgets.QLabel(self.groupBox_3)
        self.zeroBalanceLabel.setObjectName("zeroBalanceLabel")
        self.gridLayout_4.addWidget(self.zeroBalanceLabel, 0, 2, 1, 1)
        self.scaleBalanceHelp = QtWidgets.QLabel(self.groupBox_3)
        self.scaleBalanceHelp.setObjectName("scaleBalanceHelp")
        self.gridLayout_4.addWidget(self.scaleBalanceHelp, 1, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(OptimineExport)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(OptimineExport)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pressureFileLabel.setBuddy(self.pressureLineEdit)
        self.acousticsFileLabel.setBuddy(self.acousticsLineEdit)
        self.testReportLabel.setBuddy(self.testReportLineEdit)
        self.pressureVesselLabel.setBuddy(self.pressureVesselLineEdit)
        self.operatorLabel.setBuddy(self.operaatorLineEdit)
        self.pressureTransducerLabel.setBuddy(self.pressureTransducerLineEdit)
        self.startTimeLabel.setBuddy(self.dateTimeEdit)
        self.endTimeLabel.setBuddy(self.dateTimeEdit_2)
        self.partNumberLabel.setBuddy(self.partNumberLineEdit)
        self.serialNumberLabel.setBuddy(self.serialNumberLineEdit)
        self.fullScaleLabel.setBuddy(self.fullScaleSpinBox)
        self.zeroBalanceLabel.setBuddy(self.zeroBalanceSpinBox)

        self.retranslateUi(OptimineExport)
        QtCore.QMetaObject.connectSlotsByName(OptimineExport)
        OptimineExport.setTabOrder(self.pressureLineEdit, self.pressureFileButton)
        OptimineExport.setTabOrder(self.pressureFileButton, self.acousticsLineEdit)
        OptimineExport.setTabOrder(self.acousticsLineEdit, self.acousticsFileButton)
        OptimineExport.setTabOrder(self.acousticsFileButton, self.testReportLineEdit)
        OptimineExport.setTabOrder(self.testReportLineEdit, self.pressureVesselLineEdit)
        OptimineExport.setTabOrder(self.pressureVesselLineEdit, self.operaatorLineEdit)
        OptimineExport.setTabOrder(self.operaatorLineEdit, self.pressureTransducerLineEdit)
        OptimineExport.setTabOrder(self.pressureTransducerLineEdit, self.dateTimeEdit)
        OptimineExport.setTabOrder(self.dateTimeEdit, self.dateTimeEdit_2)
        OptimineExport.setTabOrder(self.dateTimeEdit_2, self.partNumberLineEdit)
        OptimineExport.setTabOrder(self.partNumberLineEdit, self.serialNumberLineEdit)
        OptimineExport.setTabOrder(self.serialNumberLineEdit, self.plainTextEdit)
        OptimineExport.setTabOrder(self.plainTextEdit, self.fullScaleSpinBox)
        OptimineExport.setTabOrder(self.fullScaleSpinBox, self.zeroBalanceSpinBox)
        OptimineExport.setTabOrder(self.zeroBalanceSpinBox, self.pushButton)
        OptimineExport.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, OptimineExport):
        _translate = QtCore.QCoreApplication.translate
        OptimineExport.setWindowTitle(_translate("OptimineExport", "Optimine DAT Exporter"))
        self.pressureFileLabel.setText(_translate("OptimineExport", "&Pressure Data:"))
        self.pressureFileButton.setText(_translate("OptimineExport", "..."))
        self.acousticsFileLabel.setText(_translate("OptimineExport", "&Acoustics Data:"))
        self.acousticsFileButton.setText(_translate("OptimineExport", "..."))
        self.pressureLineEdit.setPlaceholderText(_translate("OptimineExport", "Optimine JSON File"))
        self.acousticsLineEdit.setPlaceholderText(_translate("OptimineExport", "Acoustic Data File"))
        self.groupBox.setTitle(_translate("OptimineExport", "Report Info:"))
        self.testReportLabel.setText(_translate("OptimineExport", "&Test Report:"))
        self.pressureVesselLabel.setText(_translate("OptimineExport", "Pressure &Vessel:"))
        self.operatorLabel.setText(_translate("OptimineExport", "&Operator:"))
        self.pressureTransducerLabel.setText(_translate("OptimineExport", "Pressure &Trasducer:"))
        self.startTimeLabel.setText(_translate("OptimineExport", "&Start Time:"))
        self.dateTimeEdit.setDisplayFormat(_translate("OptimineExport", "M/d/yyyy hh:mm AP"))
        self.endTimeLabel.setText(_translate("OptimineExport", "&End Time:"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("OptimineExport", "M/d/yyyy hh:mm AP"))
        self.durationLabel.setText(_translate("OptimineExport", "Test Duration: "))
        self.duration.setText(_translate("OptimineExport", "Duration"))
        self.pressureUnitLabel.setText(_translate("OptimineExport", "Pressure Unit:"))
        self.pressureUnit.setToolTip(_translate("OptimineExport", "Recorded Pressure Units"))
        self.pressureUnit.setText(_translate("OptimineExport", "mpa"))
        self.groupBox_2.setTitle(_translate("OptimineExport", "Test Item Info:"))
        self.partNumberLabel.setText(_translate("OptimineExport", "&Part Number:"))
        self.partNumberLineEdit.setPlaceholderText(_translate("OptimineExport", "Item Part Number"))
        self.serialNumberLabel.setText(_translate("OptimineExport", "Serial &Number:"))
        self.serialNumberLineEdit.setPlaceholderText(_translate("OptimineExport", "Item Serial Number"))
        self.plainTextEdit.setPlaceholderText(_translate("OptimineExport", "Add test description here"))
        self.groupBox_3.setTitle(_translate("OptimineExport", "Export Options:"))
        self.fullScaleLabel.setText(_translate("OptimineExport", "&Full Scale:"))
        self.zeroBalanceLabel.setText(_translate("OptimineExport", "&Zero Balance:"))
        self.scaleBalanceHelp.setText(_translate("OptimineExport", "Use same values here that you will when importing with the \"Acoustic Reader\" LabVIEW program"))
        self.pushButton.setText(_translate("OptimineExport", "E&xport"))
        self.pushButton_2.setText(_translate("OptimineExport", "&Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptimineExport = QtWidgets.QDialog()
    ui = Ui_OptimineExport()
    ui.setupUi(OptimineExport)
    OptimineExport.show()
    sys.exit(app.exec_())

